### ISSUE TITLE
Collapsable header with stickyheader

### ISSUE THREAD

**Issue by cw-sanjeev** [iyegoroff/react-native-collapsible-header-views#13]
Currently, the header is overlapping over the sticky header. Is there any way to prevent this

**Comment by iyegoroff** [comment]
I'm not aware about this "sticky header" thing. Can you provide the code to reproduce your issue?

**Comment by jeffreyvanhees** [comment]
I think @cw-sanjeev means the `ListHeaderComponent`-prop on `<FlatList />` in combination with `stickyHeaderIndices={[0]}` to make it stick on top. The header is overlapping the `ListHeaderComponent` for 70%.

https://reactnative.dev/docs/flatlist#listheadercomponent

@cw-sanjeef

Solution is to give the `ListHeaderComponent` a marginTop and subtract this value from the header height :)
