### ISSUE TITLE
Calling `getNode()` on the ref of an Animated component is no longer necessary

### ISSUE THREAD

**Issue by pdugan20** [iyegoroff/react-native-collapsible-header-views#18]
Getting the following warning on RN 0.62.

> FlatList: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.

**Comment by iyegoroff** [comment]
You can use `animatedComponent` instead: https://github.com/iyegoroff/react-native-collapsible-header-views/blob/36ce3ca2e3938274acb3fa7641205ce6647e39a1/src/with-collapsible-header.tsx#L245-L247

**Comment by pdugan20** [comment]
Is there a code sample I can look at which describes the correct usage here? Not entirely sure by looking at the documentation how to implement this.

**Comment by iyegoroff** [comment]
https://github.com/iyegoroff/react-native-collapsible-header-views/blob/master/CollapsibleHeaderViewsExample/screens/WrappedInstanceMethods.tsx

**Comment by pdugan20** [comment]
Apologies, but I'm not understanding based on that sample. My implementation looks like this:
```
<CollapsibleHeaderFlatList
    ref={scrollRef}
    data={hikes}
    extraData={hikes}
    CollapsibleHeaderComponent={<FeedHeader city={city} />}
    headerHeight={35}
    showsVerticalScrollIndicator={false}
    keyExtractor={(item) => item.key}
    renderItem={this.renderItem}
    refreshControl={refreshControl}
    onEndReached={onEndReached}
    ListFooterComponent={this.renderFooter}
    headerContainerBackgroundColor={theme.colors.rootBackground}
    disableHeaderSnap
    bounces
/>
```

**Comment by iyegoroff** [comment]
I didn't get what do you want to achieve - just use `animatedComponent` method instead of `getNode`.

**Comment by pdugan20** [comment]
I'm not calling getNode() anywhere though, so I'm confused as to how I should implement animatedComponent(). Upgrading to RN 0.62 started throwing the warning whenever a <CollapsibleHeaderFlatList /> is loaded.

**Comment by iyegoroff** [comment]
If you are not calling `getNode`, then it is not related to rnchv. `getNode` is not called from the module.

**Comment by pdugan20** [comment]
Oh you're totally right, this is a react-navigation issue. Thanks for your help and for the great package!
