### ISSUE TITLE
onRefresh isn't working 

### ISSUE THREAD

**Issue by JinHoSo** [iyegoroff/react-native-collapsible-header-views#2]
Hi, Do you have a plan to support the onRefresh?

**Comment by iyegoroff** [comment]
Hi @JinHoSo , no I don't plan to add additional features, probably you can use just [RefreshControl](https://facebook.github.io/react-native/docs/refreshcontrol.html).

**Comment by michbil** [comment]
One small notice. RefreshControl won't work by default, because it's disabled by bounces={false} in the code of library. To override just add bounces to component props.

**Comment by najuasmgr** [comment]
Guys, can you try this... hope this solution works for you

For android you can use **progressViewOffset** for FlatList but it's only for Android. I tried it and it works fine on Android.
For example:
refreshControl={<RefreshControl progressViewOffset={200} />}

and for IOS, I havn't tried it but hope this work **contentInset**

**Comment by jschlachtenhaufen** [comment]
Anyone have luck with this? Still looking for the right combo of props...
