### ISSUE TITLE
Throws getNode() warning when used with @react-navigation/native

### ISSUE THREAD

**Issue by pdugan20** [iyegoroff/react-native-collapsible-header-views#22]
When using this in conjunction with the [@react-navigation/native useScrollTop function](https://github.com/react-navigation/react-navigation/blob/f00091d7abe50a390132a309fd57df83a4076767/packages/native/src/useScrollToTop.tsx), the following error gets thrown:

`%s: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in afuture release., FlatList`

useScrollTop works fine with the vanilla FlatList component. Any ideas how I can prevent the error from being thrown?

**Comment by iyegoroff** [comment]
Duplicate #18
