### ISSUE TITLE
Great work! but add dynamic Height

### ISSUE THREAD

**Issue by ningacoding** [iyegoroff/react-native-collapsible-header-views#4]
i need to add another view on runtime but height of CollapsibleHeaderScrollView is fixed, please add support to dynamic height.

**Comment by ningacoding** [comment]
It's as easy as:

onHeaderLayout = ({ nativeEvent: { layout } }) => {
    this.setState({ headerHeight: layout.height });
};

Header container:
<View onLayout={this.onHeaderLayout}></View>

**Comment by iyegoroff** [comment]
If you want to change the height of a header dynamically you have to change `headerHeight` prop explicitly.

**Comment by ningacoding** [comment]
why not add an option to handle it ?

**Comment by gilshaan** [comment]
Using accordion with react-native-collapsible will not dynamically change its content height.
I used a flatlist inside accordion and faced similar problem.. I solved it by setting a flag and re-rendering the view of accordion.

This is my flatlist.
`<FlatList`
`data={section.content}`
`renderItem={this.renderItem}`
`extraData={this.state.refresh}`
`ListEmptyComponent={this.ListEmptyView}`
`/>`

I re-rendered my accordion view like this when i add new content to flatlist.
`{this.state.refresh ? (`
`<View style={styles.flatlistMainContainer}>`
`<Accordion`
`sections={this.state.accordionArray}`
`activeSections={this.state.activeSections}`
`renderHeader={this.renderAccordionHeader}`
`renderContent={this.renderAccordionItem}`
`onChange={this._updateSections}`
`touchableComponent={TouchableOpacity}`
`/>`
`</View>`
`) : null}`

When i make any change in its content dynamically i will set the flag as :
`this.setState({ refresh: false }, () => {`
`this.setState({ refresh: true });`
`});`

By doing like this component refresh its content height.
