### ISSUE TITLE
Header absolute and transparent

### ISSUE THREAD

**Issue by andyr6381** [iyegoroff/react-native-collapsible-header-views#5]
Is It possible to set the scrolling list position to absolute and  headerContainerBackgroundColor="transparent" so the content sits under the header? As soon as apply absolute positioning to the list the header doesn't animate on scroll. I can work around this by setting a marginTop -HEADERHEIGHT style? thanks

**Comment by iyegoroff** [comment]
I didn't face this problem after adding `position: 'absolute'` here: https://github.com/iyegoroff/react-native-collapsible-header-views/blob/5da041f4aeac71d149dedcb84d15170027fc7094/CollapsibleHeaderViewsExample/screens/ShowAndHide.tsx#L67-L70

If you mean something different, please provide an example.
