### ISSUE TITLE
scrollToTop undefined

### ISSUE THREAD

**Issue by dcesca** [iyegoroff/react-native-collapsible-header-views#6]
Hi, I'm using CollapsibleHeaderScrollView and it works perfectly.
I need to reset scroll position to 0 if the user taps on the header but when i call scrollTo it's undefined.

In my code I set the ref:
<CollapsibleHeaderScrollView
                ref={(ref) => {
                    this.ListView_Ref = ref;
                  }} ...

...and the function...

goToTop() {
    this.ListView_Ref.scrollTo({x: 0, y: 0, animated: true});
}

...calling goToTop() gives undefined. What am I missing? Thanks

**Comment by muhamad-rizki** [comment]
try change this line:
this.ListView_Ref.scrollTo({x: 0, y: 0, animated: true});
with this line:
this.ListView_Ref.animatedComponent().getNode().scrollTo({x: 0, y: 0, animated: true});
